
CREATE SEQUENCE SUBJECT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE SUBJECT(SUBJECTID INT, NAME VARCHAR(90) , DESCRIPTION CLOB,
	CONSTRAINT ON_SUBJECT PRIMARY KEY(SUBJECTID));

CREATE SEQUENCE TOPIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE TOPIC(TOPICID INT, NAME VARCHAR(90),DESCRIPTION CLOB,TOPICID2SUBJECTID INT, 
  CONSTRAINT ON_TOPIC foreign Key(TOPICID2SUBJECTID) REFERENCES SUBJECT(SUBJECTID),
  CONSTRAINT ON_TOPIC1 PRIMARY KEY(TOPICID));

CREATE SEQUENCE QUESTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE QUESTION(QUESTIONID INT, DESCRIPTION clob , QUESTIONID2TOPICID INT, 
  CONSTRAINT ON_QUESTION foreign Key(QUESTIONID2TOPICID) REFERENCES TOPIC(TOPICID),
  CONSTRAINT ON_QUESTION1 PRIMARY KEY(QUESTIONID));
    
insert into QUESTION values(QUESTION_SEQ.nextval,'what is collection ..',2);
insert into QUESTION values(QUESTION_SEQ.nextval,'what is OOPS ..',4);
insert into QUESTION values(QUESTION_SEQ.nextval,'what is Jdbc Driver',4);


CREATE SEQUENCE OPTIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE OPTIONS(OPTIONSID INT, OPTIONSID2QUESTIONID INT, OPTIONSIDCOUNT INT, DESCRIPTION CLOB , 
  CONSTRAINT ON_OPTIONS foreign Key(OPTIONSID2QUESTIONID) REFERENCES QUESTION(QUESTIONID),
  CONSTRAINT ON_OPTIONS1 PRIMARY KEY(OPTIONSID));


CREATE SEQUENCE ANSWER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE ANSWER(ANSWERID INT , ANSWERID2QUESTIONID INT ,ANSWERID2OPTIONSID INT, 
  CONSTRAINT ON_ANSWER foreign Key(ANSWERID2QUESTIONID) REFERENCES QUESTION(QUESTIONID),
  CONSTRAINT ON_ANSWER1 foreign Key(ANSWERID2OPTIONSID) REFERENCES OPTIONS(OPTIONSID),
  CONSTRAINT ON_ANSWER2 PRIMARY KEY(ANSWERID));

CREATE SEQUENCE ADMIN_SEQ START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
 create table ADMIN(ADMINID INT , USERNAME VARCHAR(90) , PASSWORD VARCHAR(90), 
  ADMINPERMITIONID VARCHAR(90),ADMINPERMITIONPASSWORD VARCHAR(90),
  CONSTRAINT ON_ADMIN PRIMARY KEY(ADMINID));


SELECT T.TOPICID, T.NAME,T.DESCRIPTION,T.TOPICID2SUBJECTID, S.NAME 
FROM TOPIC T Inner JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID;

SELECT T.TOPICID, T.NAME,T.DESCRIPTION,T.TOPICID2SUBJECTID, S.NAME 
FROM TOPIC T Inner JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID
WHERE TOPICID IN (SELECT TOPICID FROM TOPIC
where NAME like '%c%' or DESCRIPTION like '%c%')
order by T.TOPICID;

SELECT T.TOPICID, T.NAME,T.DESCRIPTION,T.TOPICID2SUBJECTID, S.NAME 
FROM TOPIC T Inner JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID 
WHERE TOPICID IN (SELECT TOPICID FROM TOPIC 
where NAME like '%c%' or DESCRIPTION like '%c%') order by T.TOPICID;

SELECT T.TOPICID, T.NAME,T.DESCRIPTION,T.TOPICID2SUBJECTID, S.SUBJECTID, S.NAME 
FROM TOPIC T Inner JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID 
WHERE TOPICID IN (SELECT TOPICID FROM TOPIC where (upper(NAME) 

like upper('%c%') or upper(DESCRIPTION) like upper('%c%'))and TOPICID2SUBJECTID=1) order by T.TOPICID;

SELECT * FROM TOPIC WHERE ((upper(NAME) LIKE upper('%c%') or DESCRIPTION LIKE upper('%c%')) and topicid2subjectid=2);

SELECT T.TOPICID, T.NAME,T.DESCRIPTION,T.TOPICID2SUBJECTID, S.NAME  
FROM TOPIC T Inner JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID 
WHERE TOPICID IN (SELECT TOPICID FROM TOPIC where upper(NAME) 
like upper('%%') or upper(DESCRIPTION) like upper('%%')) 
order by T.TOPICID;


SELECT T.TOPICID, T.NAME,T.DESCRIPTION,T.TOPICID2SUBJECTID, S.NAME  
FROM TOPIC T Inner JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID 
WHERE TOPICID IN (SELECT TOPICID FROM TOPIC where (upper(NAME) 
like upper('%%') or upper(DESCRIPTION) like upper('%%')) 
AND TOPICID2SUBJECTID = 1 ) order by T.TOPICID;


SELECT Q.QUESTIONID, Q.DESCRIPTION,Q.QUESTIONID2TOPICID ,T.TOPICID , 
T.NAME AS TOPICNAME ,S.SUBJECTID, S.NAME AS SUBNAME FROM QUESTION Q 
INNER JOIN TOPIC T ON Q.QUESTIONID2TOPICID = T.TOPICID
INNER JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID
WHERE QUESTIONID IN (SELECT QUESTIONID FROM QUESTION 
where ( upper(DESCRIPTION) like upper('%%'))
AND S.SUBJECTID = 1 ) order by Q.QUESTIONID;

SELECT Q.QUESTIONID, Q.DESCRIPTION,Q.QUESTIONID2TOPICID ,T.TOPICID , 
T.NAME AS TOPICNAME ,S.SUBJECTID, S.NAME AS SUBNAME FROM QUESTION Q 
INNER JOIN TOPIC T ON Q.QUESTIONID2TOPICID = T.TOPICID
INNER JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID
WHERE QUESTIONID IN (SELECT QUESTIONID FROM QUESTION 
where ( upper(DESCRIPTION) like upper('%%')) 
AND Q.QUESTIONID2TOPICID = 4 ) order by Q.QUESTIONID;


SELECT Q.QUESTIONID, Q.DESCRIPTION,Q.QUESTIONID2TOPICID ,T.TOPICID , 
T.NAME AS TOPICNAME ,S.SUBJECTID, S.NAME AS SUBNAME FROM QUESTION Q 
INNER JOIN TOPIC T ON Q.QUESTIONID2TOPICID = T.TOPICID
INNER JOIN SUBJECT S ON T.TOPICID2SUBJECTID = S.SUBJECTID
WHERE QUESTIONID IN (SELECT QUESTIONID FROM QUESTION 
where upper(DESCRIPTION) like upper('%%')) order by Q.QUESTIONID;

SELECT * from subject;
SELECT * FROM QUESTION;
select * from options;
SELECT * FROM TOPIC;



create table samples(id int PRIMARY KEY,name varchar(90));

